routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//json
Route::post('/submit_login','LoginController@submitLogin')->name('loginwoy');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/data/akreditasi/json', 'AkreditasiController@dataTable')->name('table.akreditasi');
Route::get('/data/dokumentasi/json', 'DokumentasiController@dataTable')->name('table.dokumentasi');
Route::get('/data/kemahasiswaan/json', 'KemahasiswaanController@dataTable')->name('table.kemahasiswaan');
Route::get('/data/kegiatan/json', 'KegiatanController@dataTable')->name('table.kegiatan');
Route::get('/data/akreditasi/json/{id_prodi}', 'AkreditasiController@dataTable');
Route::get('/data/kegiatan/json/{id_prodi}', 'KegiatanController@dataTable');
Route::get('/data/kemahasiswaan/json/{id_prodi}', 'KemahasiswaanController@dataTable');
Route::get('/data/akademik/json/{id_prodi}', 'AkademikController@dataTable');
Route::get('/data/kemahasiswaan/json/{id_prodi}?', 'AkreditasiController@dataTable');
Route::get('/data/pegawai/json', 'PegawaiController@dataTable')->name('table.pegawai');
Route::get('/data/pegawai/json/{id_prodi}', 'PegawaiController@dataTable');
Route::get('/data/akademik/json', 'AkademikController@dataTable')->name('table.akademik');
Route::get('/data/jenis_berkas/json', 'TipeberkasController@dataTable')->name('table.jenis_berkas');
Route::get('/data/user_role/json', 'UserRoleController@dataTable')->name('table.user_role');
Route::get('/data/menu_role/json', 'MenuRoleController@dataTable')->name('table.menu_role');
Route::get('/data/role/json', 'RoleSettingController@dataTable')->name('table.role');

Route::post('/ganti_password', 'HomeController@ganti_password')->name('ganti_password');

//recource
Route::resource('akreditasi', 'AkreditasiController');
Route::resource('pegawai', 'PegawaiController');
/*Route::resource('staff/dosen', 'DosenController');*/
Route::resource('akademik', 'AkademikController');
Route::resource('kemahasiswaan', 'KemahasiswaanController');
Route::resource('jenis_berkas', 'TipeberkasController');
Route::resource('kegiatan', 'KegiatanController');
Route::resource('dokumentasi', 'DokumentasiController');
Route::resource('user_role', 'UserRoleController');
Route::resource('menu_role', 'MenuRoleController');
Route::resource('role_setting', 'RoleSettingController');

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/dashboard', 'HomeController@index')->name('home');

Route::get('/cari/pegawai/json', 'PegawaiController@loadData');
Route::get('/cari/user/json', 'UserRoleController@loadData');
Route::get('/prodi/json', 'AkreditasiController@prodi');
Route::get('/filter', 'AkreditasiController@filter');
Route::post('/upload/json', 'BerkasController@upload_berkas')->name('upload.berkas');

Route::get('data/document/{id}', 'BerkasController@getDocument')->name('getDocument');

app/Http/Controllers/MenuRoleController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Akreditasi;
use App\Prodi;
use App\Fakultas;
use App\TipeBerkas;
use DataTables;
use App\User;
use App\Pegawai;
use App\Berkas;
use App\Akademik;
use App\Menu;
use Auth;
use App\UserRole;
use App\RoleMenu;
use App\Role;
class MenuRoleController extends Controller
{
      /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('menu_role.index');
    }

    public function prodi()
    {
        $prodi = Prodi::all();
        return response()->json($prodi);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
          $model = new TipeBerkas();
          $tipe = TipeBerkas::all();
          $user = Auth::id();
          $menu = Menu::all();
          $role = Role::all();
         return view('menu_role.form', ['model'=> $model, 'tipe' => $tipe, 'user' => $user, 'menu' => $menu, 'role' => $role]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function store(Request $request)
    {
        $content = new RoleMenu;
        $content -> id_role = $request -> id_role;
        $content -> menu_id = $request -> menu_id;
        $content -> c = $request -> c;
        $content -> u = $request -> u;
        $content -> d = $request -> d;
        $content -> save();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   

        $model = RoleMenu::findOrFail($id);
        return view('menu_role.show', compact('model'));
    }

    public function form()
    {

        
        return view('menu_role.form', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function edit($id)
    {   
          $model = RoleMenu::findOrFail($id);
          $tipe = RoleMenu::all();
          $user = Auth::id();
          $menu = Menu::all();
          $role = Role::all();
         return view('menu_role.form_edit', ['model'=> $model, 'tipe' => $tipe, 'user' => $user, 'menu' => $menu, 'role' => $role]);
    }

    /**
     * Update the specified resource in storage.
     * 
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $content = RoleMenu::findOrFail($id);
        $content -> id_role = $request -> id_role;
        $content -> menu_id = $request -> menu_id;
        $content -> c = $request -> c;
        $content -> u = $request -> u;
        $content -> d = $request -> d;
        $content -> save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = RoleMenu::findOrFail($id);
        $model->delete();
    }

    public function loadData(Request $request)
    {
         $cari = $request->q;
            if($cari != null){
                 $data = User::where('name', 'like', "%$cari%")->orWhere('username', 'like', "%$cari%")->get();
                return response()->json($data);
            }  
    }

     public function modal()
    {
        $user = Auth::user()->username;
        $Pegawai = Pegawai::select('unit_kerja')->where('nip', $user)->get();
        foreach ($Pegawai as $key) {
            $fakultas = Fakultas::select('id_fakultas')->where('kode_fakultas', $key->unit_kerja)->get();

            foreach ($fakultas as $key) {
               $prodi = Prodi::where('id_fakultas', $key->id_fakultas)->get();
            }
        }
        return view('menu_role.form', ['prodi' => $prodi]);
    }

    public function dataTable()
    {
        
        $model = RoleMenu::with('Role', 'Menu')->get();
        return DataTables::of($model)
            ->addColumn('action', function ($model) {
                return view('layouts._action', [
                    'model' => $model,
                    'url_show' => route('menu_role.show', $model->id),
                    'url_edit' => route('menu_role.edit', $model->id),
                    'url_destroy' => route('menu_role.destroy', $model->id)
                ]);
            })
            ->addIndexColumn()
            ->rawColumns(['action'])
            ->make(true);
    }
}

resources/views/menu_role/filter.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Akreditasi Menu
          <a href="{{ route('akreditasi.create') }}" class="btn btn-success pull-right modal-show" style="margin-top: -8px;" title="Tambah Berkas Akreditasi"><i class="icon-plus"></i> Tambah</a>
      </h3>
    </div>
      <div class="form-group">
        <form method="GET"></form>
       <select id="prodi" class="form-contol">
         <option id="op_prodi">--pilih prodi--</option>

          <?php foreach ($prodi as $key): ?>
            <option value="{{ $key->id_prodi }}">{{ $key -> nama_prodi }}</option>
           
          <?php endforeach ?>
       </select>

       <button class="btn-success" id="filter">Filter</button>
      </div>
</div>
@endsection

resources/views/menu_role/form.blade.php
<form action="{{ route('menu_role.store') }}" method="POST" id="form_save">
   @csrf
  <div class="form-group">
    <label class="label-controller">Pilih Role</label>
  	<select name="id_role" class="form-control">
    	<option>---Pilih Role----</option>
    	<?php foreach ($role as $key): ?>
    		
    		<option value="{{$key->id}}">{{ $key->nama_role }}</option>
    	<?php 

    	endforeach ?>
    	
    </select>
  </div> 
  <div class="form-group">
    <label class="label-controller">Pilih Menu</label>
    <select name="menu_id" class="form-control">
      <option>---Pilih Menu----</option>
      <?php foreach ($menu as $key): ?>
        @if($key->parent != 0)
        <option value="{{$key->id}}">{{ $key->nama_menu }}</option>
        @endif
      <?php 
      endforeach ?>
    </select>
  </div>
  <div class="form-group">
  <label class="label-control">Hak Akses</label>
   <input type="checkbox" name="c" value="1"> Create
   <input type="checkbox" name="u" value="1"> Update
   <input type="checkbox" name="d" value="1"> Delete
  </div>
  </div>
  <div class="form-group">
      <button type="submit" class="btn btn-success">Save</button>
  </div>
</form>

<script>
  
    $('#form_save').submit(function (event) {
            event.preventDefault();
            var form = $('#form_save'),
            url = form.attr('action'),
            method =  'POST';
            form.find('.help-block').remove();
            form.find('.form-group').removeClass('has-error');
            var data = new FormData($('#modal-body form')[0]);
            $.ajax({
            url : url,
            method: method,
            /*data : form.serialize(),*/
            data : data,
            contentType: false,
            processData: false,
            success: function (response) {
              
                form.trigger('reset');
                $('#modal').modal('hide');
                $('#datatable').DataTable().ajax.reload();
                swal({
                    type : 'success',
                    title : 'Success!',
                    text : 'Data has been saved!'
                });
            },
            error : function (xhr) {
                var res = xhr.responseJSON;
                if ($.isEmptyObject(res) == false) {
                    $.each(res.errors, function (key, value) {
                        $('#' + key)
                            .closest('.form-group')
                            .addClass('has-error')
                            .append('<span class="help-block"><strong>' + value + '</strong></span>');
                    });
                }
            }
        })
    });
    </script>

resources/views/menu_role/form_edit.blade.php
<form action="{{Route('menu_role.update', $model->id)}}" method="PUT" name="formName" id="form_edit" >
  @csrf
   
    <div class="form-group">
      <label class="label-controller">Pilih Role</label>
      <select name="id_role" class="form-control">
        <option>---Pilih Role----</option>
        <?php foreach ($role as $key): ?>
          <option value="{{$key->id}}">{{ $key->nama_role }}</option>
        <?php 
  
        endforeach ?>
        
      </select>
    </div> 
    <div class="form-group">
      <label class="label-controller">Pilih Menu</label>
      <select name="menu_id" class="form-control">
        <option>---Pilih Menu----</option>
        <?php foreach ($menu as $key): ?>
          @if($key->parent != 0)
          <option value="{{$key->id}}">{{ $key->nama_menu }}</option>
          @endif
        <?php 
        endforeach ?>
      </select>
    </div>
    <div class="form-group">
    <label class="label-control">Hak Akses</label>
     <input type="checkbox" name="c" value="1"> Create
     <input type="checkbox" name="u" value="1"> Update
     <input type="checkbox" name="d" value="1"> Delete
    </div>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
  </form>

<script>
  
$('#form_edit').submit(function (event) {
    event.preventDefault();
        $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
        });
        var form = $('#form_edit'),
        url = form.attr('action'),
        method = 'PUT';

        form.find('.help-block').remove();
        form.find('.form-group').removeClass('has-error');
        var data = form.serialize()

  

    $.ajax({
        url : url,
        method: method,
        /*data : form.serialize(),*/
        data : data,
        success: function (response) {
          
            form.trigger('reset');
            $('#modal').modal('hide');
            $('#datatable').DataTable().ajax.reload();

            swal({
                type : 'success',
                title : 'Success!',
                text : 'Data has been saved!'
            });
        },
        error : function (xhr) {
            var res = xhr.responseJSON;
            if ($.isEmptyObject(res) == false) {
                $.each(res.errors, function (key, value) {
                    $('#' + key)
                        .closest('.form-group')
                        .addClass('has-error')
                        .append('<span class="help-block"><strong>' + value + '</strong></span>');
                });
            }
        }
    })
});
</script>

resources/views/menu_role/index.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Setting Menu Role
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard" class="active"></i> Setting Menu Role</a></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Daftar Menu Role</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fa fa-minus"></i></button>
            </div>
        </div>
        <div class="box-body">
            <div class="panel-heading">
              
            <a href="{{ route('menu_role.create') }}" class="btn btn-success pull-right modal-show" style="margin-top: -8px;" title="Tambah Berkas Akreditasi"><i class="icon-plus"></i> Tambah</a>
      
            </div>
            <br>
            <div class="panel-body">
                <table id="datatable" class="table table-hover" style="width:70%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Role</th>
                            <th>Kategori</th>
                            <th>Create</th>
                            <th>Update</th>
                            <th>Delete</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
          </div>
        </div>
    </div>
    <!-- /.box-body -->
    
    <!-- /.box-footer-->
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->
@endsection

@push('scripts')
    <script>

        $('#datatable').DataTable({
          responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('table.menu_role') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'id'},
                {data: 'role.nama_role', name: 'role.nama_role'},
                {data: 'menu.nama_menu', name: 'menu.nama_menu'},
                {data: 'c',},
                {data: 'u',},
                {data: 'd',},
                {data: 'action', name: 'action'}
            ]
        });

         $('.cari').select2({
        placeholder: 'Cari...',
        ajax: {
        url: '/cari',
        dataType: 'json',
        delay: 250,
        processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.nama_prodi,
              id: item.id_prodi
              }
            })
          };
        },
        cache: true
        }
        });




    </script>
@endpush

resources/views/menu_role/show.blade.php
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Menu</th>
        <th>Role</th>

    </tr>
    <tr>
        <td>{{ $model->id }}</td>
        <td>{{ $model->Menu->nama_menu }}</td>
        <td>{{ $model->Role->nama_role }}</td>
        
    </tr>
</table>