routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//json
Route::post('/submit_login','LoginController@submitLogin')->name('loginwoy');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/data/akreditasi/json', 'AkreditasiController@dataTable')->name('table.akreditasi');
Route::get('/data/dokumentasi/json', 'DokumentasiController@dataTable')->name('table.dokumentasi');
Route::get('/data/kemahasiswaan/json', 'KemahasiswaanController@dataTable')->name('table.kemahasiswaan');
Route::get('/data/kegiatan/json', 'KegiatanController@dataTable')->name('table.kegiatan');
Route::get('/data/akreditasi/json/{id_prodi}', 'AkreditasiController@dataTable');
Route::get('/data/kegiatan/json/{id_prodi}', 'KegiatanController@dataTable');
Route::get('/data/kemahasiswaan/json/{id_prodi}', 'KemahasiswaanController@dataTable');
Route::get('/data/akademik/json/{id_prodi}', 'AkademikController@dataTable');
Route::get('/data/kemahasiswaan/json/{id_prodi}?', 'AkreditasiController@dataTable');
Route::get('/data/pegawai/json', 'PegawaiController@dataTable')->name('table.pegawai');
Route::get('/data/pegawai/json/{id_prodi}', 'PegawaiController@dataTable');
Route::get('/data/akademik/json', 'AkademikController@dataTable')->name('table.akademik');
Route::get('/data/jenis_berkas/json', 'TipeberkasController@dataTable')->name('table.jenis_berkas');
Route::get('/data/user_role/json', 'UserRoleController@dataTable')->name('table.user_role');
Route::get('/data/menu_role/json', 'MenuRoleController@dataTable')->name('table.menu_role');
Route::get('/data/role/json', 'RoleSettingController@dataTable')->name('table.role');

Route::post('/ganti_password', 'HomeController@ganti_password')->name('ganti_password');

//recource
Route::resource('akreditasi', 'AkreditasiController');
Route::resource('pegawai', 'PegawaiController');
/*Route::resource('staff/dosen', 'DosenController');*/
Route::resource('akademik', 'AkademikController');
Route::resource('kemahasiswaan', 'KemahasiswaanController');
Route::resource('jenis_berkas', 'TipeberkasController');
Route::resource('kegiatan', 'KegiatanController');
Route::resource('dokumentasi', 'DokumentasiController');
Route::resource('user_role', 'UserRoleController');
Route::resource('menu_role', 'MenuRoleController');
Route::resource('role_setting', 'RoleSettingController');

Auth::routes();
Route::get('/', 'HomeController@index');
Route::get('/dashboard', 'HomeController@index')->name('home');

Route::get('/cari/pegawai/json', 'PegawaiController@loadData');
Route::get('/cari/user/json', 'UserRoleController@loadData');
Route::get('/prodi/json', 'AkreditasiController@prodi');
Route::get('/filter', 'AkreditasiController@filter');
Route::post('/upload/json', 'BerkasController@upload_berkas')->name('upload.berkas');

Route::get('data/document/{id}', 'BerkasController@getDocument')->name('getDocument');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $table = 'role';
}

resources/views/role/filter.blade.php
@extends('layouts.app')

@section('content')
<div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Akreditasi Menu
          <a href="{{ route('akreditasi.create') }}" class="btn btn-success pull-right modal-show" style="margin-top: -8px;" title="Tambah Berkas Akreditasi"><i class="icon-plus"></i> Tambah</a>
      </h3>
    </div>
      <div class="form-group">
        <form method="GET"></form>
       <select id="prodi" class="form-contol">
         <option id="op_prodi">--pilih prodi--</option>

          <?php foreach ($prodi as $key): ?>
            <option value="{{ $key->id_prodi }}">{{ $key -> nama_prodi }}</option>
           
          <?php endforeach ?>
       </select>

       <button class="btn-success" id="filter">Filter</button>
      </div>
</div>
@endsection

resources/views/role/form.blade.php
<form action="{{ route('role_setting.store') }}" method="POST" id="form_create">
   @csrf
  <div class="form-group">
    <label class="label-control">Nama Role</label>
  	<input type="text" name="role" class="form-control">
  </div> 
  
  <div class="form-group">
      <button type="submit" class="btn btn-success">Save</button>
  </div>
</form>

<script>
$('#form_save').submit(function (event) {
  event.preventDefault();
  var form = $('#form_save'),
  url = form.attr('action'),
  method =  'POST';
  form.find('.help-block').remove();
  form.find('.form-group').removeClass('has-error');
  var data = new FormData($('#modal-body form')[0]);
  $.ajax({
  url : url,
  method: method,
  /*data : form.serialize(),*/
  data : data,
  contentType: false,
  processData: false,
  success: function (response) {
    
      form.trigger('reset');
      $('#modal').modal('hide');
      $('#datatable').DataTable().ajax.reload();
      swal({
          type : 'success',
          title : 'Success!',
          text : 'Data has been saved!'
      });
  },
  error : function (xhr) {
      var res = xhr.responseJSON;
      if ($.isEmptyObject(res) == false) {
          $.each(res.errors, function (key, value) {
              $('#' + key)
                  .closest('.form-group')
                  .addClass('has-error')
                  .append('<span class="help-block"><strong>' + value + '</strong></span>');
          });
      }
  }
})
});
</script>

resources/views/role/form_edit.blade.php
<form action="{{Route('role_setting.update', $model->id)}}" method="PUT" name="formName" id="form_edit" >
  @csrf
  <div class="form-group">
      <label class="label-control">Nama Role</label>
  <input type="text" name="role" class="form-control" value="{{ $model->nama_role }}">
    </div> 
    
    <div class="form-group">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>

<script>
  
$('#form_edit').submit(function (event) {
    event.preventDefault();
        $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
        });
        var form = $('#form_edit'),
        url = form.attr('action'),
        method = 'PUT';

        form.find('.help-block').remove();
        form.find('.form-group').removeClass('has-error');
        var data = form.serialize()

  

    $.ajax({
        url : url,
        method: method,
        /*data : form.serialize(),*/
        data : data,
        success: function (response) {
          
            form.trigger('reset');
            $('#modal').modal('hide');
            $('#datatable').DataTable().ajax.reload();

            swal({
                type : 'success',
                title : 'Success!',
                text : 'Data has been saved!'
            });
        },
        error : function (xhr) {
            var res = xhr.responseJSON;
            if ($.isEmptyObject(res) == false) {
                $.each(res.errors, function (key, value) {
                    $('#' + key)
                        .closest('.form-group')
                        .addClass('has-error')
                        .append('<span class="help-block"><strong>' + value + '</strong></span>');
                });
            }
        }
    })
});
</script>

resources/views/role/index.blade.php
@extends('layouts.master')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Setting Role
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard" class="active"></i> Setting Role</a></li>
    </ol>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Daftar Role</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                    title="Collapse">
                    <i class="fa fa-minus"></i></button>
            </div>
        </div>
        <div class="box-body">
            <div class="panel-heading">
              
              
          <a href="{{ route('role_setting.create') }}" class="btn btn-success pull-right modal-show" style="margin-top: -8px;" title="Tambah Role"><i class="icon-plus"></i> Tambah</a></h3>
            </div>
            <br>
            <div class="panel-body">
                <table id="datatable" class="table table-hover" style="width:70%">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Role</th>
                            
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
          </div>
        </div>
    </div>
    <!-- /.box-body -->
    
    <!-- /.box-footer-->
    </div>
    <!-- /.box -->

</section>
<!-- /.content -->
@endsection

@push('scripts')
    <script>

        $('#datatable').DataTable({
          responsive: true,
            processing: true,
            serverSide: true,
            ajax: "{{ route('table.role') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'id'},
                {data: 'nama_role', name: 'nama_role'},
                
                {data: 'action', name: 'action'}
            ]
        });

         $('.cari').select2({
        placeholder: 'Cari...',
        ajax: {
        url: '/cari',
        dataType: 'json',
        delay: 250,
        processResults: function (data) {
        return {
          results:  $.map(data, function (item) {
            return {
              text: item.nama_prodi,
              id: item.id_prodi
              }
            })
          };
        },
        cache: true
        }
        });




    </script>
@endpush

resources/views/role/show.blade.php
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Nama Role</th>
        <th>Create</th>
        <th>Update</th>
        <th>Delete</th>

    </tr>
    <tr>
        <td>{{ $model->id }}</td>
        <td>{{ $model->nama_role }}</td>
        <td>{{ $model->c }}</td>
        <td>{{ $model->u }}</td>
        <td>{{ $model->p }}</td>
        
    </tr>
</table>